name: on_boarding
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-282.2.beta <4.0.0'

dependencies:
  country_flags: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  lucide_icons: ^0.257.0
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  geolocator: ^13.0.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/profile-pic.jpg
